### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by double-fault** [gavindinubilo/random-dilbert#2]
Looks like the random-dilbert site is down. Is this a temporary error, or has this project been discontinued?

**Comment by dinubs** [comment]
Project hasn't worked in sometime, if you're still interested in it I can set it up to deploy to `now` and zeit.co

**Comment by double-fault** [comment]
@dinubs sure, please do it if you can! I actually used the project to fetch random dilbert comics.

**Comment by dinubs** [comment]
Great, I'll do it tonight :D I'm also gonna host it at random-dilbert.wtf to make it easier to get to.

**Comment by dinubs** [comment]
Updated it here: https://github.com/dinubs/random-dilbert/pull/3

**Comment by double-fault** [comment]
Nice, thanks a lot!
