### ISSUE TITLE
Is Heroku down ?

### ISSUE THREAD

**Issue by ParagRaut** [gavindinubilo/random-dilbert#4]
I tried to access API but seems like heroku is offline. Any idea ?
Screenshot:
![image](https://user-images.githubusercontent.com/16030809/82807341-db957480-9e87-11ea-8fd8-4d873652a95a.png)

**Comment by double-fault** [comment]
The site had been shifted by the owner quite a long time ago. https://random-dilbert.wtf/

https://github.com/dinubs/random-dilbert/issues/2#issuecomment-476844160

**Comment by ParagRaut** [comment]
@fortunate-man oops sorry and thanks 😊
